export const skills = [
  "Strategic Sourcing",
  "Supplier Development",
  "Vendor Negotiation",
  "International Procurement",
  "RFQ & Quotation Analysis",
  "Purchase Order Management",
  "SAP S/4HANA",
  "Inventory Management",
  "Supply Chain Management",
  "Industrial Automation",
  "PLC",
  "HMI",
  "SCADA",
  "AutoCAD",
  "MATLAB",
  "Project Coordination",
  "Cost Optimization",
] as const;